<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Undefined.StringDumper.Core.Tests</AssemblyName>
    <RootNamespace>Undefined.StringDumper.Core.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Undefined.StringDumper.Core\Undefined.StringDumper.Core.csproj" />
  </ItemGroup>
</Project>
