<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Undefined.StringDumper.Core</AssemblyName>
    <RootNamespace>Undefined.StringDumper.Core</RootNamespace>
    <Version>0.4.0</Version>
  </PropertyGroup>
</Project>
